---
title: " Etude de l'impact de la concentration de pm 2.5 sur l'ésperence de vie"
output: html_document
---
"Nous allons"
```{r echo=FALSE,include= FALSE}

library(readxl)
library(dplyr)
library(stargazer)
library(lmtest)
library(sandwich)
library(whitestrap)
library(corrplot)
library(ggplot2)
library(plotly)
data = read_excel("C:/Users/hassan/Desktop/econometrie/M1 Econometrie/combined_data.xlsx")
```

**Nous commencons par voir les statistique déscriptives et les correlations**


```{r,echo=T}
stargazer(as.data.frame(data), 
          type = "text",
          title = "Table: Descriptive statistics of some variables",
          covariate.labels = c("Esperance de vie", "Part urbanistation","Concentration pm2,5", "pib","pib en milliard"))
corrplot(cor(data[-1]), method = 'square',  diag = F, addCoef.col ='black', number.cex = 0.7)


```


```{r,warning=FALSE}

plot_ly (data= data,
  x = data$pm25, y = data$espevie,
  type = "scatter",
  mode = "markers",
  text = ~`Country Name`
  )
```
**Ce graphique présente l'ésperence de vie a la naissance en fonction de la concentration de PM 2.5**

Nous commencons d'abord par voir un modèle de regression linéaire simple en prenant le logaritme de l'esperence de vie et de la concentration de pm 2.5
```{r}
modlogl <- lm(log(espevie)~log(pm25), data = data)
summary(modlogl)

ggplot(data) +
  aes(x = log(pm25), y = log(espevie)) +
  geom_point(size = 2L, colour = "#B22222") +
  theme_minimal()+
  geom_smooth(method = "lm", se = FALSE, linewidth = 1)

```


```{r}
modlogl6 <- lm(log(espevie)~log(pm25)+ parturb + log(pib), data = data)
summary(modlogl6)
bptest(modlogl6)
dwtest(modlogl6)
modlogl6 = coeftest(modlogl6,vcov=vcovHC(modlogl6,type="HC0"))
stargazer(modlogl , modlogl6, type = "text", align = TRUE)
```






